spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Auth paths
            - id: auth-service-api
              uri: http://auth-ms:4000
              predicates:
                - Path=/auth/api/v1/**
              filters:
                - RewritePath=/auth/api/v1/(?<path>.*), /api/v1/$\{path}

            - id: auth-swagger-ui
              uri: http://auth-ms:4000
              predicates:
                - Path=/auth/swagger/**
              filters:
                - RewritePath=/auth/swagger/(?<path>.*), /swagger-ui/$\{path}

            - id: auth-api-docs
              uri: http://auth-ms:4000
              predicates:
                - Path=/auth/v3/**
              filters:
                - RewritePath=/auth/v3/(?<path>.*), /auth/v3/$\{path}