server:
  port: 5001

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service-api
              predicates:
                - Path=/auth/api/v1/**
              filters:
                - RewritePath=/auth/api/v1/(?<path>.*), /api/v1/$\{path}
